Diplom_urban/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout


def index(request):
    return render(request, 'main/index.html')

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    """После успешной регистрации пользователь попадает на главную страницу."""
    form_class = CreationForm
    success_url = reverse_lazy('main:index')
    template_name = 'users/register.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru"> 
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/local.css' %}">
    <title>
      {% block title %}
        Контент не подвезли
      {% endblock %}
    </title>
    <style>
        .card {
            background-color: #413D4C;
            border-radius: 1em;
            padding: 1em;
        }
        .card-item {
            background-color: #413D4C;
            border-radius: 3em;
            padding: 2em;
            min-height: 100%;
        }
        .card-header {
            background-color: #413D4C;
        }
        .btn-secondary {
            background-color: #413D4C;
        }
        .list-group-item {
            background-color: #413D4C;
            color: white;
        }
        .top-buffer {
            margin-top: 30px;
        }
        .pagination > .page-item > .page-link {
            z-index: 3;
            color: white;
            background-color: #413D4C;
            border-color: #ddd;
        }
    </style>

  </head>
  <body>
    {% include 'includes/header.html' %}
    <main> 
      <div class="container py-5"> 
        {% block content %}
          Контент не подвезли
        {% endblock %}
      </div>
    </main>
  </body>
</html>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: #413D4C;">
    <div class="container">

      <a class="btn btn-one" href="{% url 'main:index'%}"><span style="color:white">
        <img src="{% static 'img/logo.png' %}" width="30" height="30">
        Urban
      </span>
      </a>

      <ul class="nav nav-pills">
          {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="btn btn-one" href="{% url 'users:logout' %}">
                      <span style="color:white">Выйти</span></a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="btn btn-one" href="{% url 'users:login' %}">
                      <span style="color:white">Войти</span></a>
                </li>
                <li class="nav-item">
                  <a class="btn btn-one" href="{% url 'users:signup' %}">
                      <span style="color:white">Регистрация</span></a>
                </li>
          {% endif %}
      </ul>
    </div>
  </nav>
</header>

templates/main/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
<style>
body {
    height: 100vh;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

h1 {
    font-family: "Montserrat Medium";
    max-width: 40ch;
    text-align: center;
    transform: scale(0.94);
    animation: scale 3s forwards cubic-bezier(0.5, 1, 0.89, 1);
}

@keyframes scale {
  100% {
    transform: scale(1);
  }
}

span {
  display: inline-block;
  opacity: 0;
  filter: blur(4px);
}

span:nth-child(1) { animation: fade-in 0.8s 0.1s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(2) { animation: fade-in 0.8s 0.2s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(3) { animation: fade-in 0.8s 0.3s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(4) { animation: fade-in 0.8s 0.4s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(5) { animation: fade-in 0.8s 0.5s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(6) { animation: fade-in 0.8s 0.6s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(7) { animation: fade-in 0.8s 0.7s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(8) { animation: fade-in 0.8s 0.8s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(9) { animation: fade-in 0.8s 0.9s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(10) { animation: fade-in 0.8s 1s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(11) { animation: fade-in 0.8s 1.1s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(12) { animation: fade-in 0.8s 1.2s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(13) { animation: fade-in 0.8s 1.3s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(14) { animation: fade-in 0.8s 1.4s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(15) { animation: fade-in 0.8s 1.5s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(16) { animation: fade-in 0.8s 1.6s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(17) { animation: fade-in 0.8s 1.7s forwards cubic-bezier(0.11, 0, 0.5, 0); }
span:nth-child(18) { animation: fade-in 0.8s 1.8s forwards cubic-bezier(0.11, 0, 0.5, 0); }

@keyframes fade-in {
    100% {
        opacity: 1;
        filter: blur(0);
    }
}

.text-center {
    text-align: center;
}
</style>

{% if user.is_authenticated %}
<center>
<h1>
    <span>Вы</span>
    <span>успешно</span>
    <span>зашли</span>
    <span>на</span>
    <span>аккаунт</span>
    <br>
    <span>Привет,</span>
    <span style="color: rgb(194, 127, 127);">{{ user }}</span>
</h1>
</center>

{% else %}
<center>
<h1>
  <span>Пора</span>
  <span>бы</span>
  <span>уже</span>
  <span>зарегистрироваться</span>
</h1>
</center>
{% endif %}
{% endblock %}

templates/users/includes/card.html
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{{ card_header }}</div>
      <div class="card-body"> <p>{{ card_body }}</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->

templates/users/login.html
{% extends 'base.html' %}

{% block title %} Страница входа {% endblock title%}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h3 class="font-weight-light my-1 text-center">Войдите</h3>
                        </div>

                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-3">Username</label>
                                            {{ form.username }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                          <label class="small mb-3">Password</label>
                                          {{ form.password }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-row my-lg-4 text-center">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                          <button name="login" class="col-md-12 btn btn-dark" id="login">Войти</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:signup' %}">Нет аккаунта? Зарегистрируйся</a><br>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'social:begin' 'google-oauth2' %}">Войдите с помощью Google</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
{% endblock content %}

templates/users/logout.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  {% with card_header='Выход' card_body='Вы вышли из своей учётной записи. Ждём вас снова!' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% block title %} Страница регистрации {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
		<div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
                        <div class="card-header justify-content-center">
                        	<h3 class="font-weight-light my-4 text-center">Создайте Аккаунт</h3>
                        </div>
                        <div class="card-body text-center">
                            <form method="POST">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <div id="form_errors">
                                            {% for key, value in form.errors.items %}
                                                <strong>{{ value }}</strong>
                                            {% endfor %}
                                        </div>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endif %}

                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-2">First Name</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-2">Last Name</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-6">
		                                <div class="form-group">
		                                	<label class="small mb-2">Username</label>
		                                    {{ form.username }}
		                                </div>
		                            </div>
                                    <div class="col-md-6">
		                                <div class="form-group">
		                                	<label class="small mb-2">Email</label>
		                                    {{ form.email }}
		                                </div>
		                            </div>
		                        </div>

                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-2">Password</label>
                                            {{ form.password1 }}
                                            {{ form.errors.password }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-2">Confirm</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group my-4">
                                    <button type="submit" class="col-md-12 btn btn-dark">Регистрация</button>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">Есть аккаунта? Войдите</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>

{% endblock content %}